---
- name: Download eve-ng
  get_url:
    url: '{{ EVE_INSTALL_SCRIPT_URL }}'
    dest: /tmp/eve-ng.sh
    mode: '0111'

- name: Upgrade apt
  apt:
    update_cache: yes
    upgrade: full
  
- name: Install eve-ng
  shell: /tmp/eve-ng.sh
  async: 1000
  poll: 0

- name: Wait for 80 port
  wait_for:
    port: 80
    delay: 60